# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
#services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

#stages:
#  - build
#  - test
#  - deploy

# Runs before all scripts in all stages
#before_script:

build:
  stage: build
  script:
   - npm install
   - npm install -g angular-cli
   - ng build
  artifacts:
   paths:
    - dist/

deploy:
  stage: deploy
  environment:
   name: production
  dependencies: build
  script: 
   - npm install -g firebase-tools
   - firebase deploy --token firebase deploy --token $FIREBASE_DEPLOY_KEY
